### ISSUE TITLE
Could it config the issue status which to be closed? Thanks.

### ISSUE THREAD

**Issue by archonwang** [smartlime/redmine_unclosed_issues#2]
@smartlime ,
Could it config the issue status which to be closed? Thanks.
I just want to define other status to be closed, and I do not want to modified the plugin code. any idea about it?

**Comment by smartlime** [comment]
Sorry, there's no configurable options but you may change in 1st and 4th lines of code: `:status_id => 3` to `:status_id => 555` or you can pass an array for multiple ids, eg: `:status_id => [111, 222, 333]`

**Comment by archonwang** [comment]
OK, Thanks
